// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type FilterBlockVal struct {
	_         structs.HostLayout
	ExpiresNs uint64
}

type FilterIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type FilterLpm4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type FilterLpm6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type FilterSrcStats struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
	Syn     uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	FilterMapAllow4          = "allow4"
	FilterMapAllow6          = "allow6"
	FilterMapBlock4          = "block4"
	FilterMapBlock6          = "block6"
	FilterMapProtect4        = "protect4"
	FilterMapProtect6        = "protect6"
	FilterMapSrc4            = "src4"
	FilterMapSrc6            = "src6"
	FilterMapStats           = "stats"
	FilterProgSentinelFilter = "sentinel_filter"
)

// LoadFilter returns the embedded CollectionSpec for Filter.
func LoadFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Filter: %w", err)
	}

	return spec, err
}

// LoadFilterObjects loads Filter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FilterObjects
//	*FilterPrograms
//	*FilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFilterObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterSpecs struct {
	FilterProgramSpecs
	FilterMapSpecs
	FilterVariableSpecs
}

// FilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterProgramSpecs struct {
	SentinelFilter *ebpf.ProgramSpec `ebpf:"sentinel_filter"`
}

// FilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterMapSpecs struct {
	Allow4   *ebpf.MapSpec `ebpf:"allow4"`
	Allow6   *ebpf.MapSpec `ebpf:"allow6"`
	Block4   *ebpf.MapSpec `ebpf:"block4"`
	Block6   *ebpf.MapSpec `ebpf:"block6"`
	Protect4 *ebpf.MapSpec `ebpf:"protect4"`
	Protect6 *ebpf.MapSpec `ebpf:"protect6"`
	Src4     *ebpf.MapSpec `ebpf:"src4"`
	Src6     *ebpf.MapSpec `ebpf:"src6"`
	Stats    *ebpf.MapSpec `ebpf:"stats"`
}

// FilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FilterVariableSpecs struct {
}

// FilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterObjects struct {
	FilterPrograms
	FilterMaps
	FilterVariables
}

func (o *FilterObjects) Close() error {
	return _FilterClose(
		&o.FilterPrograms,
		&o.FilterMaps,
	)
}

// FilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterMaps struct {
	Allow4   *ebpf.Map `ebpf:"allow4"`
	Allow6   *ebpf.Map `ebpf:"allow6"`
	Block4   *ebpf.Map `ebpf:"block4"`
	Block6   *ebpf.Map `ebpf:"block6"`
	Protect4 *ebpf.Map `ebpf:"protect4"`
	Protect6 *ebpf.Map `ebpf:"protect6"`
	Src4     *ebpf.Map `ebpf:"src4"`
	Src6     *ebpf.Map `ebpf:"src6"`
	Stats    *ebpf.Map `ebpf:"stats"`
}

func (m *FilterMaps) Close() error {
	return _FilterClose(
		m.Allow4,
		m.Allow6,
		m.Block4,
		m.Block6,
		m.Protect4,
		m.Protect6,
		m.Src4,
		m.Src6,
		m.Stats,
	)
}

// FilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterVariables struct {
}

// FilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type FilterPrograms struct {
	SentinelFilter *ebpf.Program `ebpf:"sentinel_filter"`
}

func (p *FilterPrograms) Close() error {
	return _FilterClose(
		p.SentinelFilter,
	)
}

func _FilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filter_bpfel.o
var _FilterBytes []byte
